name: CI
on:
    push:
        branches:
        - develop/#5-github-actions
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Build docker image
        uses: HidetoNiwa/SugiyamaLab-MasterThesis/.github/actions/latex@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TZ: 'Asia/Tokyo'
